### ISSUE TITLE
best_gwas_p

### ISSUE THREAD

**Issue by gustavahlberg** [hakyimlab/MetaXcan#103]

**Comment by Heroico** [comment]
`best_gwas_p` is the best `p-value` *among variants in the model*.

It doesn't report the best p-value across all of the GWAS, merely in the intersection of  a gene/intron's model and GWAS.

Best,

Alvaro

**Comment by gustavahlberg** [comment]
That was not my interpretation either. But where does the number come from? Which snp etc. 
The best_gwas_p seems a bit misleading since it implies that it is a p-value that refers to one from the GWAS itself. It also almost always the same p-value as the reported from the analysis as well.  Which in this case seem vastly vastly inflated. So it makes quite difficult to error search when there is no context to where the numbers even come from.....

**Comment by Heroico** [comment]
So, did you delete the comments or something?
