### ISSUE TITLE
PrediXcan MashR model 0% of model's snps used 

### ISSUE THREAD

**Issue by Hannah430** [hakyimlab/MetaXcan#110]
Hi MetaXcan group, 
i am trying to run PrediXcan using imputed genetic data formatted like 1:13380:C:G.However, i kept  on getting an empty file with "0% of models' sips used. I also tried to add in the line --keep_non_rsid based on a similar post on MetaXcan, but it seems to be specific to the MetaXcan program.   I am wondering if i should convert the formatting to 1_13380_C_G? Is there a command that allow me to directly force the  colon into a dash in PrediXcan? I would really appreciate to get some of your input, it will  be very helpful. Thank you very much!
Here is the command I used:
python3 ./Predict.py --model_db_path $DATA/mashr_Brain_Frontal_Cortex_BA9.db 
--model_db_snp_key varID 
--vcf_genotypes $CARTA/AxiomVCF.vcf 
--vcf_mode imputed 
--liftover $DATA/hg19ToHg38.over.chain.gz 
--on_the_fly_mapping METADATA "chr{}_{}_{}_{}_b38" 
--prediction_output $RESULT/Frontalcortex__predict.txt 
--prediction_summary_output $RESULT/frontalcortex__summary.txt 
--verbosity 9 
--throw

and here is the output:
INFO - Loading samples
INFO - Loading model
INFO - Acquiring on-the-fly mapping
INFO - Preparing genotype dosages
INFO - Acquiring liftover conversion
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
Level 9 - Processing vcfs
Level 9 - Processing vcf /mnt/sample/data/untared/AxiomVCF.vcf
INFO - 0 % of models' snps used
INFO - Storing prediction
INFO - Saving prediction as a text file
INFO - Saving summary
INFO - Successfully predicted expression in 2.8029250 seconds

Thank you very much!

**Comment by natashasanthanam** [comment]
Hi!
You could try running the same command and change `--on_the_fly_mapping METADATA "chr{}{}{}_{}_b38"` to
 `--on_the_fly_mapping METADATA "{}_{}_{}_{}"`
Let us know how it goes!

**Comment by Hannah430** [comment]
Hi!
Thank you for very much for your input,  i tried --on_the_fly_mapping METADATA "{}_{}_{}_{}" and --on_the_fly_mapping METADATA "{}_{}_{}_{}_b38"
however both still give me 0% of model's snps used. Is there any other thing i can attempt to trouble shoot? Thank you so much!

**Comment by hakyim** [comment]
your pattern is missing a couple of underscores. Can you try with the exact format provided by Natasha? 

Can you copy your command with the options here? There seem to be some issues with copy pasting extraneous characters.

**Comment by Hannah430** [comment]
Hi! 
I think the format of the dashes between the {} disappeared when i posted the post. Thank you for pointing that out. I tried Natasha's suggestion and still got 0% fo model's sips used. Here are the code I used:
`--on_the_fly_mapping METADATA "{}_{}_{}_{}"`
`--on_the_fly_mapping METADATA "{}_{}_{}_{}_b38"`
Thank you very much for your input!

**Comment by liangyy** [comment]
Hi @Hannah430, could you provide the first few lines and columns of the vcf file? For instance, could you run `cat $CARTA/AxiomVCF.vcf|grep -v '##'|head -n 2|cut -f 1-9` and paste the output here? Feel free to mask the actual genotype if there is any.

**Comment by Hannah430** [comment]
Hi @liangyy , thank you so much for your support. Here is the output (i have altered the content of the output while keeping the format):
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT
1	12345	1:12345:C:G	C	G	.	.	PR	GT

I really appreciate all the team's time and support, thank you!

**Comment by liangyy** [comment]
Hi @Hannah430, it seems that your VCF only have `GT` entry. Could you try `--vcf_mode genotyped`?

**Comment by Hannah430** [comment]
Hi @liangyy , thank you for your suggestion. I tried `--vcf_mode genotyped` alongside with `--on_the_fly_mapping METADATA "{}_{}_{}_{}"`, however i am still getting 0% of snps used.

**Comment by Hannah430** [comment]
Hi @liangyy, thank you very much for your help! i get 10 % of model's snps used. This is very strange since the the genetic data were imputed with michigan imputation server.Since i am relatively new to this field, I am wondering if this is just an annotation problem. Also whether the 10% is a "normal" percentage. I have 2% of snps used from the example provided by the MetaXcan group. Thank you so much and I appreciate all your helps!

**Comment by liangyy** [comment]
Not exactly sure which example you were running. If you were running the example with chromosome 22 only, then 2% looks fine to me since it is the only chromosome. 

For the case of your genotype, it seems that it does not have fields other than `GT` (which represents genotype). I'm not an expert on Michigan imputation server but I believe it should generate dosage field in the VCF. Maybe you could double check whether your file was successfully imputed and check the header of the resulting VCF.

**Comment by Hannah430** [comment]
Thank you very much. Yes, the 2% is from the example of chromosome 22. Using my genetic data, i have about 70% of model's snps used. I am assuming it's because the other 30% of gene are not presented in my genetic data? Will that affect the quality of the prediction? Thank you so much!

**Comment by liangyy** [comment]
Yes, it means 30% of the SNPs are not present in your genotype data. This will affect the quality of the prediction. The total number of SNPs per gene and the number of SNPs used for prediction are listed in the summary file (as part of the output).

**Comment by Hannah430** [comment]
Thank you very much for your answer!
