### ISSUE TITLE
Smallest possible p-value

### ISSUE THREAD

**Issue by basel-maher** [hakyimlab/MetaXcan#111]
Hello,

what does a p-value of 0 in S-PrediXcan mean? Is it just smaller than the smallest possible floating point number in Python (~1e-325)?

Thanks

**Comment by hakyim** [comment]
Yes. You can also check that by looking at the Zscores and calculating the p-value with the log option in R, for example.

pnorm(-abs(Zscore) ), na.rm = TRUE), log.p = TRUE)
