### ISSUE TITLE
Attribute Error; run(args) 

### ISSUE THREAD

**Issue by vic-dragon** [hakyimlab/MetaXcan#115]
I am trying to run Predict.py script for applying MASHR model.

- My VCF file does not have rsid.

I used your example 5. It is hg38-based genotype

printf "Predict expression\n\n"

python3   $dir/Predict.py \
--model_db_path $dir/mashr_Whole_Blood.db \
--model_db_snp_key varID \
--vcf_genotypes  $dir/predixcan.blood.vcf.gz \
--vcf_mode genotyped \
--prediction_output $dir/Whole_Blood__predict.txt  \
--prediction_summary_output $dir/Whole_Blood__summary.txt \
--verbosity 9 \
--throw \
--variant_mapping $dir/gtex_v8_eur_filtered_maf0.01_monoallelic_variants.txt.gz id rsid \
--on_the_fly_mapping METADATA "{}_{}_{}_{}_b38" 

I keep getting the following error message
---
INFO - Loading samples
INFO - Loading model
INFO - Acquiring variant mapping
INFO - Acquiring on-the-fly mapping
INFO - Preparing genotype dosages
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
Level 9 - Processing vcfs
Level 9 - Processing vcf predixcan.blood.vcf.gz
INFO - 0 % of models' snps used
INFO - Storing prediction
Traceback (most recent call last):
  File "Predict.py", line 270, in <module>
    run(args)
  File "Predict.py", line 218, in run
    results.store_prediction()
AttributeError: 'NoneType' object has no attribute 'store_prediction'

**Comment by liangyy** [comment]
Hi @vic-dragon, sorry for the inconvenience, I messed up this part in the last commit. I have created a PR to fix it. At the meantime, you could either checkout branch `issue115` or checkout the previous commit `122e5fd1c94cd7b3c1a68ad80a5e199d10244f77` as workaround.
