### ISSUE TITLE
A question about MetaXcan

### ISSUE THREAD

**Issue by Cobbybaby** [hakyimlab/MetaXcan#121]
Hi ,Thank you for your tools. i think it is very useful.
Can it only make predictions for a few organizations (such as, 13 Brains tissues) together rather than all tissues(49 tissues).
Beacuse it throws an error "AttributeError: 'NoneType' object has no attribute 'group", when  i just run 13 Brain tissues.

so I run it using spredixcan in 13 brain tissues models ,then , i  run smetaxcan with 13 spredixcan results in the spredxcan/eqtl file(.csv). But it throw a error "No intersection between model names in MetaXcan Results and Prediction Models. Please verify your input".
Thank you. Looking forward to your reply.

**Comment by Heroico** [comment]
Hi Cobby,

You can run SPrediXcan and SMultiXcan with only a subset of tissues. For Example, `SMultiXcan` has a  `--models_name_filter` and `--metaxcan_filter` parameters - you can use a regular expression containing `Brain` according to the result names you used for `SPrediXcan`.

Another "manual" way is just srtting up a model and covariance folder containing your 13 tissues of interest.

The error you mentioned means that MultiXcan couldn't match model files to SPrediXcan result files - this must be done by passing arguments reflecting the names of your choice. Feel free to paste here your SPrediXcan and SMultiXcan command line instructions.

Best,

Alvaro

**Comment by Cobbybaby** [comment]
Thank you very much, I solve the question after changing the "--models_name_patter"( it was used in the github for a example ) to "--models_name_filter"( which uesd in&nbsp; your&nbsp; replay). I try to learn this tool.&nbsp; Have a nice day!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alvaro ***@***.***&gt;; 
发送时间: 2021年3月19日(星期五) 凌晨4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hakyimlab/MetaXcan] A question about MetaXcan (#121)





 
Hi Cobby,
 
You can run SPrediXcan and SMultiXcan with only a subset of tissues. For Example, SMultiXcan has a  --models_name_filter and --metaxcan_filter parameters - you can use a regular expression containing Brain according to the result names you used for SPrediXcan.
 
Another "manual" way is just srtting up a model and covariance folder containing your 13 tissues of interest.
 
The error you mentioned means that MultiXcan couldn't match model files to SPrediXcan result files - this must be done by passing arguments reflecting the names of your choice. Feel free to paste here your SPrediXcan and SMultiXcan command line instructions.
 
Best,
 
Alvaro
