### ISSUE TITLE
ERROR in hg19-based genotype, on GTEx v8 MASHR Model

### ISSUE THREAD

**Issue by EEEleanor** [hakyimlab/MetaXcan#127]
Dear MetaXcan team:
I got a problem here about variant mapping. I ran the Predict.py to predict gene expression with hg19-based genotype data. Genotype data is preprocessed by the script [https://github.com/hakyimlab/PrediXcan/blob/master/Software/convert_plink_to_dosage.py]. And some of them didn't have rsIDs.,like 22:17063121_AAAAG_A. But "File "KeyError: 'TA' " showed up. The script is
python Predict.py --model_db_path /mashr/mashr_Lung.db --model_db_snp_key varID --text_genotypes ./chr22.txt.gz --text_sample_ids ./chr22.sam --liftover ./liftover/hg19ToHg38.over.chain.gz --on_the_fly_mapping METADATA "chr{}_{}_{}_{}_b38" --prediction_output ./chr22_wb.txt --prediction_summary_output ./chr22_wb_summary.txt --verbosity 9 --throw

INFO - Loading samples
INFO - Loading model
INFO - Acquiring on-the-fly mapping
INFO - Preparing genotype dosages
INFO - Acquiring liftover conversion
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
Level 9 - Processing Dosage geno ./chr22.txt.gz
Traceback (most recent call last):
  File "/software/MetaXcan/MetaXcan-master/software/Predict.py", line 272, in <module>
    run(args)
  File "/software/MetaXcan/MetaXcan-master/software/Predict.py", line 176, in run
    for i,e in enumerate(dosage_source):
  File "/software/MetaXcan/MetaXcan-master/software/metax/genotype/DosageGenotype.py", line 60, in dosage_files_geno_lines
    for e in dosage_file_geno_lines(f, variant_mapping=variant_mapping, whitelist=whitelist, skip_palindromic=skip_palindromic, liftover_conversion=liftover_conversion):
  File "/software/MetaXcan/MetaXcan-master/software/metax/genotype/DosageGenotype.py", line 41, in dosage_file_geno_lines
    _id, id = Genomics.maybe_map_variant(id, chrom, pos, ref_allele, alt_allele, variant_mapping, is_dict_mapping)
  File "/software/MetaXcan/MetaXcan-master/software/metax/misc/Genomics.py", line 106, in maybe_map_variant
    varid = variant_mapping(chr, pos, ref, alt)
  File "/software/Predict.py", line 126, in <lambda>
    mapping = lambda chromosome, position, ref_allele, alt_allele: Genomics.coordinate_format(checklist, args.on_the_fly_mapping[1], chromosome, position, ref_allele, alt_allele)
  File "/software/MetaXcan/MetaXcan-master/software/metax/misc/Genomics.py", line 12, in coordinate_format
    c = format.format(chromosome, position, nt[ref_allele], nt[alt_allele])
KeyError: 'TA'

Thanks a lot!

Lin

**Comment by liangyy** [comment]
Hi Lin, I suspect that the issue is caused by a recent update. I added the fix at #128. The PR is still pending but you can give it a try by checking out branch `issue127`.

**Comment by t-monf** [comment]
Hello! I was getting the same error as EEEleanor above; I tried the branch issue127 and I am now getting the followingerror :

INFO - Loading samples
INFO - Loading model
INFO - Acquiring on-the-fly mapping
INFO - Preparing genotype dosages
INFO - Acquiring liftover conversion
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
Level 9 - Processing vcfs
Level 9 - Processing vcf TEST.vcf.gz
Traceback (most recent call last):
  File "/nfs_home/users/tsmf/software/MetaXcan/software/Predict.py", line 272, in <module>
    run(args)
  File "/nfs_home/users/tsmf/software/MetaXcan/software/Predict.py", line 176, in run
    for i,e in enumerate(dosage_source):
  File "/nfs_home/users/tsmf/software/MetaXcan/software/metax/genotype/CYVCF2Genotype.py", line 76, in vcf_files_geno_lines
    liftover_conversion=liftover_conversion):
  File "/nfs_home/users/tsmf/software/MetaXcan/software/metax/genotype/CYVCF2Genotype.py", line 62, in vcf_file_geno_lines
    d = numpy.apply_along_axis(lambda x: x[0], 1, variant.format("DS"))
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/nfs_home/users/tsmf/anaconda3/envs/TWAS/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 363, in apply_along_axis
    axis = normalize_axis_index(axis, nd)
numpy.AxisError: axis 1 is out of bounds for array of dimension 0

Thanks for your help!
Thomas

**Comment by liangyy** [comment]
Hi @t-monf, it seems that you used `--vcf_mode imputed`? Internally, the script will try to use `DS` information in the VCF. Could you check if the DS entries are not empty?

**Comment by t-monf** [comment]
Thanks for your reply. Yes I have indeed used --vcf_mode imputed.
I had a look at my vcf, it seem that DS field is present but not for all. 

4       68786   rs10030871      T       C       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       69567   rs6599368       A       T       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       69713   rs7678633       G       A       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       70334   rs147473864     A       G       .       .       .       GT:DS   0/0     0/0     0/0     0/0     0/0     0/0
4       70392   rs13130581      A       G       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       71566   rs13125929      T       C       .       .       .       GT      0/0     0/0     0/0     0/1     0/0     0/0
4       72048   rs6839041       T       G       .       .       .       GT:DS   0/0:0.0079      0/0     0/0     0/1     0/0     0/0
4       72303   rs6851329       A       G       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       72510   rs11734652      T       C       .       .       .       GT:DS   0/1     0/0     0/1     0/0     0/0     0/0
4       72592   rs782065960     ATGTAAG A       .       .       .       GT:DS   0/0     0/0     0/0     0/0     0/0     0/0
4       72939   rs10027065      T       C       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       73508   rs4690284       C       T       .       .       .       GT:DS   1/1     1/1     1/1     1/1     1/1     0/1
4       73981   rs13119939      G       A       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       74015   rs6599371       A       G       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       74238   rs13125667      G       A       .       .       .       GT:DS   0/0     0/0     0/0     0/1     0/0     0/0
4       74298   rs73217968      T       C       .       .       .       GT:DS   0/0     0/0     0/0     0/0     0/0     0/0
4       74473   rs139959875     A       G       .       .       .       GT:DS   0/0:0.0039      0/1     0/0     0/0     0/1     0/0
...
4       86031   rs782176882     CA      C       .       .       .       GT:DS   1/1     ./.:1.5294      1/1:1.9961      1/1     ./.:1.2941      1/1

When trying --vcf-mode genotyped, predict.py seems to work.

I am not used to work with vcf files; I started from imputed genotypes bgen files and converted them to vcf with plink with:
plink2  --bgen myinput.bgen ref-first --export vcf vcf-dosage=DS --out myoutput

**Comment by liangyy** [comment]
hmm .. I've not encountered this issue before. 
I pasted the notes for `vcf-dosage` for plink2 here [link](https://www.cog-genomics.org/plink/2.0/data):

_Dosage are not exported unless the 'vcf-dosage=' modifier is present. The following five dosage export modes are supported:
'GP': genotype posterior probabilities (v4.3 only).
'DS': Minimac3-style dosages, omitted for hardcalls.
'DS-force': Minimac3-style dosages, never omit.
'HDS': Minimac4-style phased dosages, omitted for hardcalls and unphased calls. Also includes 'DS' output.
'HDS-force': Always report DS and HDS._

According to this, could you try `vcf-dosage=DS-force`?

**Comment by t-monf** [comment]
it makes sense, I'll give it a go!
