### ISSUE TITLE
Predict.py using CommonMind model - 0 % of models' snps used

### ISSUE THREAD

**Issue by FernandaSantos13** [hakyimlab/MetaXcan#147]
Dear MetaXcan team,

I've been trying to run Predic.py in my data using CMC prediction model. After running the following code: 

python3 Predict.py \
--model_db_path data/weights/Downloads/CMC_DLPFC-PrediXcan_Models/DLPFC_newMetax.db \
--text_genotypes data/dosages/* \
--text_sample_ids data/dosages/samples.txt \
--prediction_output results/DLPFC_CMC_20220202.h5 HDF5 \
--prediction_summary_output results/DLPFC_CMC_20220202_summary.txt \
--verbosity 1 \
--throw

I got the following output:
INFO - Loading samples
INFO - Loading model
INFO - Preparing genotype dosages
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
INFO - 0 % of models' snps used
INFO - Saving summary
INFO - Successfully predicted expression in 8.552547761704773 seconds

My input files are in dosage text format and variants are in rsID format (file name chr10.txt.gz):
10 rs4468273 96469 G A 0.2485 0 0 2 0 0 1 0 2 1 1 1 2 0 0 0 2 1 1 1 0 0 0 1 0 0 1 2 0 2 1 0 0 0 1 0 0 0 0 0   ...
10 rs4266997 96434 C T 0.266 1 1 0 1 2 0 0 0 0 0 0 0 1 2 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 2 0 0.532 0 0 1 ...

I've also checked the CMC model .db file and it is also using rsID, so I can't find what I am missing here. Would you have any thoughts on that?

Thank you in advance and best regards,

Fernanda

**Comment by Fnyasimi** [comment]
Hi @FernandaSantos13  the possible solutions are addressed [here](https://predictdb.org/post/2021/07/20/error-0-snps-used/)

**Comment by FernandaSantos13** [comment]
Hi @Fnyasimi 
thank you for your reply. Both the genotype and summary stats uses rsID to identify the variants (the model is ElasticNet). However, my genotype file was actually in the hg19 build. So I applied the solution suggested on the link. But it still did not work. See below:

python3 Predict.py \
> --model_db_path data/weights/Downloads/gtex_v7_Brain_Cortex_imputed_europeans_tw_0.5_signif.db \
> --text_genotypes data/dosages/* \
> --text_sample_ids data/dosages/samples.txt \
> --prediction_output results/brain_cortex_GTEXv7_20220318.h5 HDF5 \
> --prediction_summary_output results/brain_cortex_GTEXv7_20220318_summary.txt \
> --on_the_fly_mapping METADATA "chr{}_{}_{}_{}_b38" \
> --verbosity 1 \
> --throw

INFO - Loading samples
INFO - Loading model
INFO - Acquiring on-the-fly mapping
INFO - Preparing genotype dosages
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
Level 9 - Creating HDF5 prediction repository
Level 9 - Creating prediction dataset
Level 9 - Creating genes
Level 9 - Creating samples
Level 9 - created HDF5 prediction repository
Level 9 - closing HDF5 prediction repository
INFO - 0 % of models' snps used
INFO - Saving summary
INFO - Successfully predicted expression in 3.675226892810315 seconds

I even tried with another database that has been previously used by us on the deprecated version of PrediXcan (GTEX v7), but it did not work with any database used.

**Comment by Fnyasimi** [comment]
@FernandaSantos13 can you manually check if the SNPs present in your genotype are present in the database? 
When using on the fly mapping, the `METADATA "chr{}{}{}_{}_b38"` should be set to the pattern in the `varID` column of the database weights table. The pattern differs depending on the build e.g for hg19 based models it wold look like this `chr{}{}{}_{}_b37` or `{}{}{}_{}_b37`.   You also need the `--model_db_snp_key` argument set to `varID` instead of `rsid`. If the genome build is different from the model you will also need a liftover chain provided via `--liftover` argument

**Comment by FernandaSantos13** [comment]
It ended up working after I converted my dosage files to vcf format and removed the extension .h5 HDF5 from my output. The final solution was:

python3 Predict.py \
--model_db_path data/weights/Downloads/gtex_v7_Brain_Cortex_imputed_europeans_tw_0.5_signif.db \
--vcf_genotypes /external/rprshnas01/eslab/fsantos/DNS_genotypes/vcf/chr*.vcf \
--vcf_mode genotyped \
--model_db_snp_key rsID \
--prediction_output results/DNS_Brain_Cortex_gtex_v7_20220405.txt  \
--prediction_summary_output results/DNS_Brain_Cortex_gtex_v7_20220405_summary.txt \
--verbosity 1 \
--throw

INFO - Loading samples
INFO - Loading model
INFO - Preparing genotype dosages
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
Level 9 - Processing vcfs
Level 9 - Processing vcf 
INFO - 85 % of models' snps used
INFO - Storing prediction
INFO - Saving prediction as a text file
INFO - Saving summary
INFO - Successfully predicted expression in 1641.4814672535285 seconds
