### ISSUE TITLE
S-MultiXcan results files - not all genes from individual tissues present

### ISSUE THREAD

**Issue by DoraCChen** [hakyimlab/MetaXcan#169]
Hello MetaXcan team!

I was comparing S-MultiXcan results files to results from individual tissue PrediXcan and noticed that a small subset of genes from individual tissue results were not present in the multiple-tissue MultiXcan results. **Is this behavior to be expected,** or does it indicate an issue with the setup of the MultiXcan pipeline itself? I would have expected every gene that has a single-tissue model to also be included in the cross-tissue model, but can imagine that it might be discarded due to LD mismatch or during SVD.

**Comment by Heroico** [comment]
Hi, what you observe is expected, and you are right in considering problems like the SVD algorithm. In the datasets I've troubleshooted so far, the SVD decomposition is the most frequent cause of failures to compute the multi-tissue results. 

LD mismatch by itself could cause numerical imprecision, but I haven't observed failure to yield a result only from LD mismatch. The numerical imprecision might itself cause additional complications for the SVD algorithm to converge if the inferred correlation between predicted expression is close to degenerate.

Increasing the logging levels might give you additional information like `"Problems with inverse for %s, skipping"`. YOu can modify code around [here](https://github.com/hakyimlab/MetaXcan/blob/master/software/metax/cross_model/JointAnalysis.py) to additional debugging/troubleshooting information.

**Comment by DoraCChen** [comment]
Thank you for the confirmation!
