### ISSUE TITLE
S_MultiXcan error (GWAS.py script)

### ISSUE THREAD

**Issue by hellsgate666** [hakyimlab/MetaXcan#183]
Hi,

I am trying to run S-MultiXcan using the following command:
`$path/MetaXcan/software/SMulTiXcan.py \
--models_folder $path/MetaXcan/GTExv8_models/MASHR/mashr_eqtl/eqtl/mashr \
--models_name_pattern "mashr_(.*).db" \
--snp_covariance snp_covar.txt \
--metaxcan_folder $path/MetaXcan/S_Predixcan/results \
--metaxcan_file_name_parse_pattern "Spredixcan_predix_(.*).txt" \
--gwas_folder $path/MetaXcan/S_Predixcan/GWAS/ \
--gwas_file_pattern "GWAS_liftedover_hg38_with_MarkerName_all_tissues.txt" \
--snp_column MarkerName \
--effect_allele_column EA \
--non_effect_allele_column OA \
--beta_column Effect \
--pvalue_column Pvalue \
--model_db_snp_key varID \
--keep_non_rsid \
--cutoff_condition_number 30 \
--verbosity 7 \
--throw \
--output $path/MetaXcan/S_MultiXcan/S_MultiXcan_11Oct2023.txt`

But it gives the following error:
`INFO - Processing input gwas
Traceback (most recent call last):
  File "$path/MetaXcan/software/SMulTiXcan.py", line 93, in <module>
    run(args)
  File "$path/MetaXcan/software/SMulTiXcan.py", line 22, in run
    context = CrossModelUtilities.context_from_args(args)
  File "$path/MetaXcan/software/metax/cross_model/Utilities.py", line 186, in context_from_args
    intersection = GWASAndModels.gwas_model_intersection(args)
  File "$path/MetaXcan/software/metax/misc/GWASAndModels.py", line 36, in gwas_model_intersection
    gwas= GWASUtilities.load_plain_gwas_from_args(args)
  File "$path/MetaXcan/software/metax/gwas/Utilities.py", line 116, in load_plain_gwas_from_args
    files = [_l(x) for x in files]
  File "$path/MetaXcan/software/metax/gwas/Utilities.py", line 116, in <listcomp>
    files = [_l(x) for x in files]
  File "$path/MetaXcan/software/metax/gwas/Utilities.py", line 109, in <lambda>
    _l = lambda x: GWAS.load_gwas(x, gwas_format, skip_until_header=args.skip_until_header,
  File "$path/MetaXcan/software/metax/gwas/GWAS.py", line 109, in load_gwas
    d = _rename_columns(d, gwas_format)
UnboundLocalError: local variable 'd' referenced before assignment`

Does the metaxcan team or anyone know how to resolve this error? It seems like it is facing issues in handling the GWAS summary statistics file data frame. We have also tried to use the `--separator "\t"` option. 

Any guidance on this matter will be appreciated.

Sincerely,
Hridya

**Comment by Hanuphant** [comment]
Implemented a fix to the source code to limit arbitrariness. 

In the file MetaXcan/software/metax/gwas/GWAS.py
```
d = pandas.read_table(source, separator)
```

was edited to
```
d = pandas.read_table(source, sep = separator, engine='python')
```
Alternatively, you can use the base Python on your Linux machine or Python v.3.6.8. I was shocked to see that Python v3.6.8 doesn't require the fix but v3.9.5 does require the fix.

**Comment by hellsgate666** [comment]
Thank you!

**Comment by hellsgate666** [comment]
Thank you!
