### ISSUE TITLE
Request to include chromosome number , gene name and positions in sqlite db files

### ISSUE THREAD

**Issue by veera-dr** [hakyimlab/MetaXcan#43]
Hi,

Just a request. Will it be possible to include the SNP positions (some specific build), chromosome numbers and also gene names (HUGO) in the sqlite db files ?

Thank you

**Comment by hakyim** [comment]
Hi Veera

The gene names are located in the SQLite dbs. In the extras table. As for
the chromosome numbers and position we can provide the annotation file. It
seems that the dbs would become larger that we would like. But let me think
about whether to include that information within each db.

Haky

**Comment by veera-dr** [comment]
Hi Haky,

Thanks for the reply. I didn't notice that gene name column in extra. It will be really helpful for downstream analysis and plotting, if you could either add the chromosome and positions in the db file or provide them as a separate download. For now I manually get that information from UCSC data base and there are some transcripts in the predictions that don't exist in UCSC database. 

Thank you 

Regards 
Veera

**Comment by hakyim** [comment]
Hey Scott

Could you show Veera where to find the annotation files he needs?

Thanks
Haky

**Comment by ScottPDickinson** [comment]
Hi Veera,

All of the annotation info is available on the GTEx portal.  To get this data:

1. Go to GTEx portal (gtexportal.org)
2. Log in, or create a free account if you haven't already done so. GTEx requires you to create an account before can download its data 
3. At the top of the page, navigate to Datasets -> Download 
4. For the snp annotation, scroll towards the bottom and click on "GTEx Analysis V6 (dbGaP Accession phs000424.v6.p1)" 
5. Under Reference, download the file "GTEx_Analysis_v6_OMNI_genot_1KG_imputed_var_chr1to22_info4_maf01_CR95_CHR_POSb37_ID_REF_ALT.txt.gz" 
6. For the gene annotation, download the file "gencode.v19.genes.v6p_model.patched_contigs.gtf.gz" listed under Reference for v6p.

The snp annotation file contains the chr_pos_ref_alt_build notation for the snp as well as the rsid numbers for dbSNP135 and dbSNP142. The rsid numbers from dbSNP142 correspond to those in our newly released models.

**Comment by hakyim** [comment]
Thank you Scott. Maybe we should add this question+answer to the FAQ?

Haky

**Comment by veera-dr** [comment]
Hi Scott and Haky,

Thanks a lot for the detailed answer. :)

-- 
Veera Manikandan
Sent with Airmail

On 4 November 2016 at 5:00:34 PM, Hae Kyung Im (notifications@github.com) wrote:

Thank you Scott. Maybe we should add this question+answer to the FAQ?

Haky
