### ISSUE TITLE
geno2pheno db access

### ISSUE THREAD

**Issue by kevinVervier** [hakyimlab/MetaXcan#58]
Hi,

I would like to know if there is a way to export the query table we get from the website (http://prelim.hakyimlab.org/gene2pheno/). For instance, I am looking for a way to save all the p-values for a given pair of phenotype-tissue.
Thank you,

Kevin

**Comment by Heroico** [comment]
Hi Kevin,

We have rendered the SQL database underlying gene2pheno into an sqlite file (around 4gb). If this works, I can share it with you.

**Comment by kevinVervier** [comment]
That may work. Thanks.

**Comment by Heroico** [comment]
Great! I sent you an email asking for some details.
