### ISSUE TITLE
Error message: "INFO - Unexpected error: nothing to repeat"

### ISSUE THREAD

**Issue by cassyrc** [hakyimlab/MetaXcan#59]
**Hi, I'm trying to use MetaXcan on some results from a meta-analysis GWAS study. The study results are in a whitespace-delimited file (meta_08092017_combined.TBL), like this:** 
MarkerName Allele1 Allele2 Freq1 FreqSE MinFreq MaxFreq Effect StdErr P.value Direction
rs17216707 t c 0.7971 0.0041 0.7916 0.8037 0.0451 0.0051 1.182e-18 ?-++?+?+
rs6127099 a t 0.7189 0.0067 0.7016 0.7231 0.0449 0.0052 4.106e-18 ?-?+?+?+
rs4074995 a g 0.2625 0.0553 0.05 0.2848 -0.0344 0.0042 2.631e-16 ----+---
rs209955 t c 0.2627 0.061 0.05 0.2978 -0.0367 0.0045 7.252e-16 -+?-----
rs17217119 a g 0.8034 0.0445 0.7844 0.95 0.0425 0.0054 2.374e-15 ++?+++?+
rs11746443 a g 0.2507 0.0582 0.05 0.2768 -0.0361 0.0046 5.683e-15 --?-----
rs687289 a g 0.3192 0.0811 0.05 0.3624 0.0338 0.0044 8.91e-15 ++?+-+++
rs11741640 a g 0.269 0.0025 0.2675 0.276 -0.0385 0.005 1.571e-14 ?-?-?-?-
rs209957 a g 0.7326 0.0585 0.7016 0.95 0.0324 0.0042 1.968e-14 +-++++++

**I've tried the MetaXcan command, as follows:**
$ ./MetaXcan.py \
> --model_db_path data/DGN-WB_0.5.db \
> --covariance data/covariance.DGN-WB_0.5.txt.gz \
> --gwas_folder data/GWAS \
> --gwas_file_pattern "*.TBL" \
> --snp_column MarkerName \
> --effect_allele_column Allele1 \
> --non_effect_allele_column Allele2 \
> --beta_column Effect \
> --pvalue_column P.value \
> --output_file results/fgf23.csv

**and get the following error:**
INFO - Unexpected error: nothing to repeat

**I've also tried the M03_betas command, as follows, with the same error.** 
$ ./M03_betas.py \
> --model_db_path data/DGN-WB_0.5.db \
> --output_folder temp/beta_f \
> --gwas_folder data/GWAS \
> --gwas_file_pattern "*.TBL" \
> --snp_column MarkerName \
> --non_effect_allele_column Allele2 \
> --effect_allele_column Allele1 \
> --beta_column Effect \
> --pvalue_column P.value
INFO - Unexpected error: nothing to repeat

**Everything works just fine when I'm running the example.** 

**Any thoughts as to what might be going on?** 

**Thanks!!**

**Cassy****

**Comment by Heroico** [comment]
Hi Cassy!

May I ask you to add `--throw` to your command line instruction, and then paste the output?

Thanks!

**Comment by cassyrc** [comment]
Thanks for getting back to me! 

Here's the output when I include --throw in the command line:

Traceback (most recent call last):
  File "./MetaXcan.py", line 92, in <module>
    run(args)
  File "./MetaXcan.py", line 26, in run
    g = M03_betas.run(args)
  File "/mnt/c/Users/robinc3/Downloads/MetaXcan/software/M03_betas.py", line 80, in run
    regexp = re.compile(args.gwas_file_pattern) if args.gwas_file_pattern else  None
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat

**Comment by Heroico** [comment]
I think I know what the problem is. This is a "feature" of python's regular expressions.

May I ask you to try with the following modification to `gwas_file_pattern`?

```
...
--gwas_file_pattern ".*TBL" 
...
```

Please let me know if this works.

**Comment by cassyrc** [comment]
It worked! Thank you so much and have a great weekend!

**Comment by Heroico** [comment]
Great!
