### ISSUE TITLE
Unexpected error in test case

### ISSUE THREAD

**Issue by AlexHatoum** [hakyimlab/MetaXcan#65]
Hello,

I have been following along with your online example and have been running the appropriate modules (python 2.7.10 and all correct versions of the module, the compiler is gcc). When I attempt to run the example script (starts with ./MetaXcan.p \) I get the warning "INFO - unexpected error: 'module' object no attribute 'to_numeric'.  

Is there an easy fix to this issue?  

Thanks

**Comment by Heroico** [comment]
Hi Alex!

I have never experienced that error. I have some questions:

1) What example are you referring to? The one in the Github's Readme? Which example script?
2) Which version of MetaXcan are you running? (Can be seen in `./MetaXcan.py --help`

Can you show me a full stack trace of the error? You can do that by running the same command with an additional parameter: `--throw`

**Comment by AlexHatoum** [comment]
Thanks,

1.  Yes on the Readme.
2.  When I run the --help flag I get: 
  File "./MetaXcan.py", line 12, in <module>
    from metax.gwas import Utilities as GWASUtilities
  File "/work/ics/data/projects/friedmanlab/studies/Bioinformatics/MetaXcan-master/software/metax/gwas/Utilities.py", line 81
    s = {c:[] for c in header_comps}
                ^
3.  I get a similar error with the --throw flag

Traceback (most recent call last):
  File "./MetaXcan.py", line 12, in <module>
    from metax.gwas import Utilities as GWASUtilities
  File "/work/ics/data/projects/friedmanlab/studies/Bioinformatics/MetaXcan-master/software/metax/gwas/Utilities.py", line 81
    s = {c:[] for c in header_comps}
                ^
SyntaxError: invalid syntax
./PrediXcanRun: line 17: --throw: command not found

**Comment by Heroico** [comment]
I can think of two things.

First, if running `MetaXcan.py --help` throws such an error, it looks like there is a problem with the environment. For example, the right version of python may not be not picked up by the environment (the line in question is perfectly valid python 2.7 syntax). I would try running `python --version` and `which python` to confirm.

The following `./PrediXcanRun: line 17: --throw: command not found` suggests there is a problem with the instruction used to run metaxcan. That error is exactly what happens if you run `--throw` on a bash shell. I assume this is a bash script you are running. Could you please share with me this `PrediXcanRun` file?

**Comment by AlexHatoum** [comment]
Thanks,

I am running python 2.7.10

This is the script 


load scipy
ml load pandas
ml load numpy 

./MetaXcan.py \
--model_db_path data/DGN-WB_0.5.db \
--covariance data/covariance.DGN-WB_0.5.txt.gz \
--gwas_folder data/GWAS \
--gwas_file_pattern ".*gz" \
--snp_column SNP \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column BETA \
--pvalue_column P \
--output_file results/test.csv
--throw

Alex

**Comment by Heroico** [comment]
Is this meant to be run on a cluster?

Also, in bash or similar environments, if you have split the instruction into multiple lines, you need to use a `\` character at the end of each line. Like in:

```
./MetaXcan.py \
--model_db_path data/DGN-WB_0.5.db \
--covariance data/covariance.DGN-WB_0.5.txt.gz \
--gwas_folder data/GWAS \
--gwas_file_pattern ".*gz" \
--snp_column SNP \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column BETA \
--pvalue_column P \
--output_file results/test.csv \
--throw
```

**Comment by AlexHatoum** [comment]
Yes,

Yes, sorry, I typed out the script and didn't paste it. 

The issue was with the compiler, I apologize for using up your time and thank you for the assistance.  I was able to get the test case to work correctly.   This is a very interesting program and I am glad to see that such a response team is developing it.

Alex
