### ISSUE TITLE
new GTEx release

### ISSUE THREAD

**Issue by IoannaTachmazidou** [hakyimlab/MetaXcan#70]
Dear MetaXcan authors, 

I understand there has been recently a new GTEx release. Are you planning to update the GTEx data that come with your software? If not, would it be easy for a user to transform the GTEx release into the format needed for MetaXcan?  Apologies, if that's a naive question, I have not investigated if the format is straightforward.

Best,
Ioanna

**Comment by Heroico** [comment]
Dear Ioanna,

We are currently working on GTEx Version 7 data; we are verifying the generated models and taking the opportunity to improve model reporting. We don't have an ETA but they should be done pretty soon.

For the sake of completeness, we make the software for training models available [here](https://github.com/hakyimlab/PredictDBPipeline). You can find the input formats and documentation documented there, and in its wiki.

Also, I recommend joining our [mail list](https://groups.google.com/forum/#!forum/predixcanmetaxcan) for news and updates on releases.

Best,

Alvaro

**Comment by Heroico** [comment]
I just noticed this issue wasn't answered, sorry for the delay. We published precompiled models and LD information for GTEx v7 [here](http://predictdb.hakyimlab.org/)
