### ISSUE TITLE
error using train_models.py 

### ISSUE THREAD

**Issue by IoannaTachmazidou** [hakyimlab/MetaXcan#72]
I would like to use MetaXcan with eQTL data from Blueprint. To understand the process of creating input files for PrediXcan, I am following your tutorial with the gEUVADIS data, but I'm afraid I didn't go far. When running "python train_models.py" that submits 22 jobs to HPC, I get the errors below. Can you please advice? Many thanks!

qsub -v study=gEUVADIS,expr_RDS=../../data/intermediate/expression_phenotypes/geuvadis.expr.RDS,geno=../../data/intermediate/genotypes/geuvadis.snps.chr1.txt,gene_annot=../../data/intermediate/annotations/gene_annotation/gencode.v12.genes.parsed.RDS,snp_annot=../../data/intermediate/annotations/snp_annotation/geuvadis.annot.chr1.RDS,n_k_folds=10,alpha=0.5,out_dir=../../data/intermediate/model_by_chr/,chrom=1,snpset=HapMap,window=1e6 -N gEUVADIS_model_chr1 -d /GWD/bioinfo/projects/RD-TSci-Software/CB/customrecipes/PredictDBPipeline/joblogs/example train_model_by_chr.pbs
qsub: ERROR! Wrong time format "/GWD/bioinfo/projects/RD-TSci-Software/CB/customrecipes/PredictDBPipeline/joblogs/example" specified to -d option

**Comment by IoannaTachmazidou** [comment]
I think I figured it out, -d was supposed to be the path to the data but our HPC thought is was time? I have replaced "-d /GWD/bioinfo/projects/RD-TSci-Software/CB/customrecipes/PredictDBPipeline/joblogs/example" with -cwd and the jobs are now running. But please bear with me,  I think I'll have more issues before I manage to do this for Blueprint...

**Comment by Heroico** [comment]
No problem!

Please be advised that questions like this are more appropriately posed in this project: https://github.com/hakyimlab/PredictDBPipeline
