### ISSUE TITLE
getLogger() message

### ISSUE THREAD

**Issue by jinghuazhao** [hakyimlab/MetaXcan#78]
Dear MetaXcan developers,

I tried to run the documentation example,,

./MetaXcan.py \
--model_db_path data/DGN-WB_0.5.db \
--covariance data/covariance.DGN-WB_0.5.txt.gz \
--gwas_folder data/GWAS \
--gwas_file_pattern ".*gz" \
--snp_column SNP \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column BETA \
--pvalue_column P \
--output_file results/test.csv

but got error message below; is there a way to fix?

Traceback (most recent call last):
  File "./MetaXcan.py", line 55, in <module>
    Logging.configureLogging(int(args.verbosity))
  File "/home/jhz22/D/genetics/hakyimlab/ftp/MetaXcan/software/metax/Logging.py", line 7, in configureLogging
    logger = logging.getLogger()
AttributeError: 'module' object has no attribute 'getLogger'

I have

uname -a
Linux jhz22-VirtualBox 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Jing Hua Zhao

**Comment by rbonazzola** [comment]
Hello Jing Hua,

Since `logging` is part of the Python Standard Library for Python 2.7, it might have to do with the version of Python you are using. Could you run `python --version` to find out which one it is?
If this is OK (i.e. if it's 2.7), inserting `print(dir(logging))` right before line 7 in `software/metax/Logging.py` could provide some insight on this issue.

Thanks,
Rodrigo

**Comment by jinghuazhao** [comment]
Dear Rodrigo,


Indeed -- I have  2.7.15~rc1-1 (Ubuntu 18.04) which gave me the error message but worked just fine under 2.7.17 (Fedora 27) -- I gather I need to fine a way to compromise.


Best wishes,




Jing Hua

________________________________

**Comment by jinghuazhao** [comment]
I can get python 2.7.14 working and will try to get around pandas, etc.


https://tecadmin.net/install-python-2-7-on-ubuntu-and-linuxmint/

<https://tecadmin.net/install-python-2-7-on-ubuntu-and-linuxmint/>

The version on Fedora was 2.7.14 not 2.7.17.


________________________________

**Comment by jinghuazhao** [comment]
It turned out that is a more difficult track.


I now fixed this by renaming Logging.py to myLogging.py and then adjusting the call from Logging to myLogging in M03_betas.py, M04_zscores.py and MetaXcan.py.


It looks the recent version of Python is stricter, which is somewhat expected as with most other compilers -- while maintaining my R packages I got a lot of complaints from g++ 8.xx which is otherwise OK with g++ 7.x.x.

________________________________

**Comment by jinghuazhao** [comment]
MetaXcan ran under both Fedora 27 (now with Python 2.7.15) and Ubuntu 18.04 (python 2.7.15r1) now.

**Comment by jinghuazhao** [comment]
I would keep a note of this, thanks!
