### ISSUE TITLE
SMultiXcan not recognizing the file pattern, unclear debugging

### ISSUE THREAD

**Issue by bcoombes** [hakyimlab/MetaXcan#79]
I am trying to run a combined tissue test using SMultiXcan.py  
 
I have run MetaXcan for all of the tissues. Now I am feeding those results into SMultiXcan.py which uses them and the original prediction files to try to combine. The error is coming when it is trying to figure out the naming structure. 

 I get this error: 
File "/projects/bsi/psych/s105109.goa/BP_Biobank/PrediXcan/MetaXcan2/MetaXcan/software/metax/metaxcan/MetaXcanResultsManager.py", line 45, in _parse_name
    pheno, model = g[0], g[1]
IndexError: tuple index out of range
 
I’m just not sure about a fix. Below is the code I am using. I have bolded the two lines which I think are causing the problem.  I need the program to connect the files (MetaXcan results and PrediXcan db models) with that pattern where (.*) is.
 
 
PROJDIR=/projects/bsi/psych/s105109.goa/BP_Biobank/PrediXcan
DBDIR=/data5/bsi/psych/s105109.goa/BP_Biobank/larry/PrediXcan/PredictDB
OUTDIR=/data5/bsi/psych/s105109.goa/BP_Biobank/batzler/PGC_Analysis/metaAnalysis_imputed/BMI.pcAdj.assoc.linear
OUTDIR2=/data5/bsi/psych/s105109.goa/BP_Biobank/WNT_Pathway/PGC
 
cd $PROJDIR/MetaXcan2/MetaXcan/software/
 
./SMulTiXcan.py \
--models_folder $DBDIR/GTEx-V6p-1KG-2016-11-16 \
--models_name_filter "TW_Brain(.*)_0.5_1KG.db" \
**--models_name_pattern "TW_Brain(.*)_0.5_1KG.db" \**
--snp_covariance $PROJDIR/MetaXcan/snps_covariance.txt.gz \
--metaxcan_folder $OUTDIR2/metaxcan_results \
--metaxcan_filter "TW_Brain(.*)_0.5_1KG.pgcbmi.caseonly.csv" \
**--metaxcan_file_name_parse_patter "TW_Brain(.*)_0.5_1KG.pgcbmi.caseonly.csv" \**
--gwas_file $OUTDIR2/ALL_BMI.pcAdj.assoc.linear_P_MAresultsFE.txt.gz \
--snp_column SNP \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column b \
--pvalue_column pval \
--cutoff_condition_number 30 \
--verbosity 7 \
--throw \
--output $OUTDIR2/brain_pgcbmi.caseonly.csv

**Comment by Heroico** [comment]
Hi there,

SMulTiXcan assumes that the metaxcan file names have two substrings of interest: the trait name first and then the tissue name. i.e. `my_trait_with_TW_Brain.csv`. 
The `metaxcan_file_name_parse_pattern` argument needs a pattern with two *groups* where the first one extracts the trait name and the second one is the tissue name. i.e. `(.*)_with_TW_(.*).csv`. In your case, I would suggest using `(.*)_Brain(.*)_0.5_1KG.pgcbmi.caseonly.csv` as a workaround. It will interpret the `TW` token as the trait name without affecting the process.

So, I advice trying something like the following:

```bash
./SMulTiXcan.py \
--models_folder $DBDIR/GTEx-V6p-1KG-2016-11-16 \
--models_name_filter ".*Brain.*db" \
--models_name_pattern "TW_Brain(.*)_0.5_1KG.db" \
--snp_covariance $PROJDIR/MetaXcan/snps_covariance.txt.gz \
--metaxcan_folder $OUTDIR2/metaxcan_results \
--metaxcan_filter "TW_Brain(.*)_0.5_1KG.pgcbmi.caseonly.csv" \
--metaxcan_file_name_parse_patter "(.*)_Brain(.*)_0.5_1KG.pgcbmi.caseonly.csv" \
--gwas_file $OUTDIR2/ALL_BMI.pcAdj.assoc.linear_P_MAresultsFE.txt.gz \
--snp_column SNP \ 
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column b \
--pvalue_column pval \
--cutoff_condition_number 30 \
--verbosity 7 \
--throw \ 
--output $OUTDIR2/brain_pgcbmi.caseonly.csv
```

**Please mind**: I infer you are using v6p models trained on 1000Genomes snps and the snp covariance downloaded from PredictDB. If this is the case, *it will not work*. Unfortunately that snp covariance is compiled for the models trained on HapMap, i.e. those from [GTEx-V6p-HapMap-2016-09-08.tar.gz](https://s3.amazonaws.com/predictdb2/deprecated/GTEx-V6p-HapMap-2016-09-08.tar.gz). There is currently no such compilation for the v6p 1KG models. I'll try to build one but I don think I'll be able to publish it before next week.

**Comment by bcoombes** [comment]
Thanks for the response. I have updated all of the files to the latest HapMap v7 data and rerun with the file you pointed to. Here is the updated script using your suggested changes: 

########################################
PROJDIR=/projects/bsi/psych/s105109.goa/BP_Biobank/coombes/PrediXcan
DBDIR=/data5/bsi/psych/s105109.goa/BP_Biobank/coombes/PrediXcan_results/GTEx-V7_HapMap-2017-11-29
OUTDIR=/data5/bsi/psych/s105109.goa/BP_Biobank/batzler/PGC_Analysis/metaAnalysis_imputed/BMI.pcAdj.assoc.linear
OUTDIR2=/data5/bsi/psych/s105109.goa/BP_Biobank/coombes/WNT_Pathway/PGC

cd $PROJDIR/MetaXcan2/MetaXcan/software/

./SMulTiXcan.py \
--models_folder $DBDIR \
--models_name_filter ".*Brain.*db" \
--models_name_pattern "gtex_v7_Brain(.*)_imputed_europeans_tw_0.5_signif.db" \
--snp_covariance $PROJDIR/MetaXcan/snp_covariance_v7.txt.gz \
--metaxcan_folder $OUTDIR2/metaxcan_results/HapMap \
--metaxcan_filter "gtex_v7_Brain(.*).pgcbmi.caseonly.csv" \
--metaxcan_file_name_parse_patter "(.*)_Brain(.*)_imputed_eur.pgcbmi.caseonly.csv" \
--gwas_file $OUTDIR2/ALL_BMI.pcAdj.assoc.linear_P_MAresultsFE.txt.gz \
--snp_column SNP \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column b \
--pvalue_column pval \
--cutoff_condition_number 30 \
--verbosity 7 \
--throw \
--output $OUTDIR2/HapMap/Brain_v7_imputed_eur.pgcbmi.caseonly.csv

###################################################

The code has now made it past the issue I mentioned above (the program can now find the correct files) but seems to have gotten stuck at another spot which I am unable to understand why. There is no clear error message here so any help on how to proceed would be appreciated. Below is the error message after about half of the genes were processed through S-MultiXcan:

...
Level 7 - Gene 8351/14505: ENSG00000138069.12
Level 7 - Gene 8352/14505: ENSG00000142330.15
Level 7 - Gene 8353/14505: ENSG00000234842.1
Level 7 - Gene 8354/14505: ENSG00000187605.11
Level 7 - Gene 8355/14505: ENSG00000222040.3
Traceback (most recent call last):
  File "./SMulTiXcan.py", line 78, in <module>
    run(args)
  File "./SMulTiXcan.py", line 28, in run
    for i,gene in enumerate(context.get_genes()):
  File "/projects/bsi/psych/s105109.goa/BP_Biobank/coombes/PrediXcan/MetaXcan2/MetaXcan/software/metax/cross_model/Utilities.py", line 62, in get_genes
    for d in self.snp_covariance_streamer:
  File "/projects/bsi/psych/s105109.goa/BP_Biobank/coombes/PrediXcan/MetaXcan2/MetaXcan/software/metax/misc/DataFrameStreamer.py", line 25, in data_frame_streamer
    if additional_skip_row_check and additional_skip_row_check(comps):
  File "/projects/bsi/psych/s105109.goa/BP_Biobank/coombes/PrediXcan/MetaXcan2/MetaXcan/software/metax/cross_model/Utilities.py", line 192, in <lambda>
    snp_covariance_streamer = DataFrameStreamer.data_frame_streamer(args.snp_covariance, "GENE", additional_skip_row_check= lambda x: _check_in(x, intersection))
  File "/projects/bsi/psych/s105109.goa/BP_Biobank/coombes/PrediXcan/MetaXcan2/MetaXcan/software/metax/cross_model/Utilities.py", line 190, in _check_in
    return comps[1] not in intersection or comps[2] not in intersection
IndexError: list index out of range

**Comment by Heroico** [comment]
That is a strange error. It seems like the code is having trouble reading the aggregated SNP covariance file. I can't reproduce it on my end.

Maybe the covariance file is corrupt? Can I ask you to run the following on the command line?

```bash
zcat /projects/bsi/psych/s105109.goa/BP_Biobank/coombes/PrediXcan/MetaXcan/snp_covariance_v7.txt.gz | wc
```
If it throws any error, then I would advice to download the file again. Please let me know how this goes, the output I see for the above is:

```
zcat snp_covariance_v7.txt.gz | wc
792534523 3170138092 44048029458
```

**Comment by bcoombes** [comment]
Thanks! The file did not fully download so only half was there. That
explains why only half of the genes ran and then it quit. Everything is now
working.
