### ISSUE TITLE
0 % of model's snps used

### ISSUE THREAD

**Issue by QidiFeng** [hakyimlab/MetaXcan#83]
Hi, MetaXcan group,

I built my own Transcriptome Model with my own data with PredictDB, and then I tried MetaXcan.py with the produced db file, covariance file and downloaded GLGC summary data. However, it always come up with no results and report ' **0 % of model's snps used**'. I have checked the format of db file and covariance file, which is exactly the same with that in provided example. I also checked that there are around 20% SNP in db overlapped with those in GLGC. So I am really confused why ' 0 % of model's snps used'. 
One thing is the rsID I used in the model and GLGC data is not formal rsID, but formatted like '10_94140_G_A_b38'. I do not like this will cause a problem since I have point out the SNP column in the command. Would you please help me to figure out where is problem is? Thank you very much!

Here is the command I used:
./MetaXcan.py \
--model_db_path /net/mulan/disk2/qidif/S-Predixcan/PredictDBPipeline/data/output/dbs/MESA_MESA_alpha0.5_window1e6_filtered.db \
--covariance /net/mulan/disk2/qidif/S-Predixcan/PredictDBPipeline/data/output/allCovariances/MESA_MESA_alpha0.5_window1e6.txt.gz \
--gwas_folder /net/mulan/disk2/qidif/S-Predixcan/Input/gwas/ \
--gwas_file_pattern "jointGwasMc_HDL.modified.2.txt" \
--snp_column SNP_hg38 \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column beta \
--pvalue_column P-value \
--output_file results/test.csv

And here are the print out:
INFO - Processing GWAS command line parameters
INFO - Building beta for jointGwasMc_HDL.modified.4.txt and /net/mulan/disk2/qidif/S-Predixcan/PredictDBPipeline/data/output/dbs/MESA_MESA_alpha0.5_window1e6_filtered.db
INFO - Reading input gwas with special handling: /net/mulan/disk2/qidif/S-Predixcan/Input/gwas/jointGwasMc_HDL.modified.4.txt
INFO - Processing input gwas
INFO - Successfully parsed input gwas in 203.336451054 seconds
INFO - Started metaxcan process
INFO - Loading model from: /net/mulan/disk2/qidif/S-Predixcan/PredictDBPipeline/data/output/dbs/MESA_MESA_alpha0.5_window1e6_filtered.db
INFO - Loading covariance data from: /net/mulan/disk2/qidif/S-Predixcan/PredictDBPipeline/data/output/allCovariances/MESA_MESA_alpha0.5_window1e6.txt.gz
/net/mulan/disk2/qidif/MetaXcan/software/metax/MatrixManager.py:31: FutureWarning: read_table is deprecated, use read_csv instead.
  d = pandas.read_table(path, sep="\s+")
INFO - Processing loaded gwas
INFO - Started metaxcan association
INFO - 0 % of model's snps used
INFO - Sucessfully processed metaxcan association in 839.607428074 seconds

**Comment by Heroico** [comment]
Hi there!

By default, MetaXcan discards non rsid variants as a safety feature. You can use free-form variant ids with the option `--keep_non_rsid`

If the problem persists, feel free to send me your data to `alvarobarbeira` `at` `gmail` `dot` `com` so that I troubleshoot on my end.

**Comment by QidiFeng** [comment]
Hi Heroico,

Command '--keep_non_rsid' did solve the problem, and now MetaXcan could process data smoothly. Thank you very much for your answer!
I have another question concerning the process of constructing models by PredixcanDB. My input expression datasets contain 17,839 ENSG genes. And the input genotype covered all input genes. While the output db file as well as other files like MESA.allBetas.txt contains results from only 12,319 ENSG genes. I am wondering if there are any filtering processes during model construction? Is it possible that I get models without gene filtering?

Best,
Qidi

**Comment by Heroico** [comment]
Hi there!

If you used `https://github.com/hakyimlab/PredictDB_Pipeline_GTEx_v7` or similar, there are indeed a few filters:
1) variants with MAF>0.01
2) genes marked as protein coding, pseudo genes, or lncRNA in the gene annotation
3) prediction models with good enough cross validated prediction performance (correlation `rho > 0.1`, prediction performance `pvalue < 0.05`, details are  here: `http://hakyimlab.org/post/2017/v7-v6p-analysis/`

1) and 2) can be customized when submitting jobs to the queue.

3) happens after running the jobs, when running `filter_dbs.R`
