### ISSUE TITLE
Unexpected error: CRC check failed

### ISSUE THREAD

**Issue by maegsul** [hakyimlab/MetaXcan#87]
Hi, 

I am testing S-PrediXcan for the first time, using the example dataset and the code:

```
wget https://s3.amazonaws.com/imlab-open/Data/MetaXcan/sample_data/v0_5/sample_data.tar.gz  

tar -xzvpf sample_data.tar.gz  

./MetaXcan.py \  
--model_db_path data/DGN-WB_0.5.db \  
--covariance data/covariance.DGN-WB_0.5.txt.gz \  
--gwas_folder data/GWAS \  
--gwas_file_pattern ".*gz" \  
--snp_column SNP \  
--effect_allele_column A1 \  
--non_effect_allele_column A2 \  
--beta_column BETA \  
--pvalue_column P \  
--output_file results/test.csv  
```

After processing the last chromosome, I get this "CRC check failed" error:

> .....
> INFO - Building beta for chr9.assoc.dosage.gz and data/DGN-WB_0.5.db
> INFO - Reading input gwas with special handling: data/GWAS/chr9.assoc.dosage.gz
> INFO - Processing input gwas
> INFO - Aligning GWAS to models
> INFO - Trimming output
> INFO - Successfully parsed input gwas in 42.6134901047 seconds
> INFO - Started metaxcan process
> INFO - Loading model from: data/DGN-WB_0.5.db
> INFO - Loading covariance data from: data/covariance.DGN-WB_0.5.txt.gz
> INFO - Unexpected error: CRC check failed 0x4ed8f5d6 != 0xc37e2172L

What might be causing this? Thanks in advance!

PS: I am working on a conda python 2.7 environment with below packages & versions:

> Name                    Version                   Build  Channel
> 
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> blas                      2.11                   openblas    conda-forge
> ca-certificates           2019.11.27                    0    anaconda
> certifi                   2019.11.28               py27_0    anaconda
> intel-openmp              2019.5                      281    anaconda
> libblas                   3.8.0               11_openblas    conda-forge
> libcblas                  3.8.0               11_openblas    conda-forge
> libffi                    3.2.1             he1b5a44_1006    conda-forge
> libgcc-ng                 9.2.0                h24d8f2e_1    conda-forge
> libgfortran               3.0.0                         1    conda-forge
> libgfortran-ng            7.3.0                hdf63c60_0    anaconda
> libgomp                   9.2.0                h24d8f2e_1    conda-forge
> liblapack                 3.8.0               11_openblas    conda-forge
> liblapacke                3.8.0               11_openblas    conda-forge
> libopenblas               0.3.6                h5a2b251_2    anaconda
> libstdcxx-ng              9.2.0                hdf63c60_1    conda-forge
> mkl                       2019.5                      281    anaconda
> mkl-service               2.3.0            py27he904b0f_0    anaconda
> mkl_fft                   1.0.10                   py27_0    conda-forge
> mkl_random                1.0.4            py27hf2d7682_0    conda-forge
> ncurses                   6.1               hf484d3e_1002    conda-forge
> numpy                     1.14.2           py27hdbf6ddf_1    anaconda
> numpy-base                1.11.3          py27h2f8d375_12    anaconda
> openblas                  0.2.19                        0    anaconda
> openmp_impl               4.5                       0_gnu    conda-forge
> openssl                   1.1.1                h7b6447c_0    anaconda
> pandas                    0.24.2           py27he6710b0_0    anaconda
> pip                       19.3.1                   py27_0    conda-forge
> python                    2.7.15            h5a48372_1009    conda-forge
> python-dateutil           2.8.1                      py_0    anaconda
> pytz                      2019.3                     py_0    anaconda
> readline                  8.0                  hf8c457e_0    conda-forge
> scipy                     1.2.1            py27he2b7bc3_0    anaconda
> setuptools                44.0.0                   py27_0    conda-forge
> six                       1.13.0                   py27_0    anaconda
> sqlalchemy                1.3.12           py27h7b6447c_0    anaconda
> sqlite                    3.30.1               hcee41ef_0    conda-forge
> tk                        8.6.10               hed695b0_0    conda-forge
> wheel                     0.33.6                   py27_0    conda-forge
> zlib                      1.2.11            h516909a_1006    conda-forge

**Comment by Heroico** [comment]
Hi there,

It looks like the data download failed. I advice to download again; I just tested it and it worked on my end.

Best,

Alvaro

**Comment by maegsul** [comment]
Hi Alvaro, it was indeed related to the data download that failed somehow. The issue is solved now, thank you very much!
