### ISSUE TITLE
Using the Gtexv8- mashr model

### ISSUE THREAD

**Issue by gpwhiz** [hakyimlab/MetaXcan#89]
Hi, 
Thank you for the updated version.
I have used the GTEX v8 mashr models. I did the GWAS harmonization using the first (or the recommended) method. I didn't impute and ran the MetaXcan.py. 
In the output file, three columns related to prediction - pred_* had all NAs.
Is there a value(parameter) I should have used to get these?

The following is my script and parameters
python2 MetaXcan/software/MetaXcan.py \
--gwas_file  mygwas-harmonize.txt.gz \
--snp_column panel_variant_id --effect_allele_column effect_allele --non_effect_allele_column non_effect_allele --zscore_column zscore \
--model_db_path data/models/eqtl/mashr/mashr_Whole_Blood.db \
--covariance data/models/eqtl/mashr/mashr_Whole_Blood.txt.gz \
--keep_non_rsid --additional_output --model_db_snp_key varID \
--throw \
--output_file mygwas-mashr-GTexV8_Whole_Blood.csv

Thank you for helping.

**Comment by Heroico** [comment]
Hi there,

The `pred*` columns do not apply to MASHR models, therefore it is expected for them to be `NA`.

The `pred*` columns detail cross-validated prediction performance, a statistic defined only on Elastic Net models. The MASHR models have no `prediction performance` measure.

BEst,

alvaro
