### ISSUE TITLE
PrediXcan - clarify predict gene expression

### ISSUE THREAD

**Issue by kkmann** [hakyimlab/MetaXcan#91]
Hi,

first of all, thanks for making these models available - much appreciated!

I would like to clarify a use-case of the published models *exclusively* for GREx prediction. If I manage to match my dosage files to the GTEx IDs in the provided models `*.db/weights` table, do I still need to run PrediXcan.py or can I just add up weights times dosage myself? 

Best wishes,

Kevin

**Comment by Heroico** [comment]
Hi Kevin,

Indeed, you can compute GREx as `\sum w_i genotypes_i` yourself.
The PrediXcan code basically loads the variants and performs this weighted sum.

Best,

Alvaro
