### ISSUE TITLE
Imputation problem

### ISSUE THREAD

**Issue by nay421** [hakyimlab/MetaXcan#95]
Hi,

I am trying to follow the steps outlined in the tutorial (https://github.com/hakyimlab/MetaXcan/wiki/Tutorial:-GTEx-v8-MASH-models-integration-with-a-Coronary-Artery-Disease-GWAS).

I am having a problem at the 'Imputation' stage when I run the example script. I get the following stdout and stderr messages:

**INFO - Beginning process
INFO - Creating context by variant
INFO - Loading study
INFO - Loading variants' parquet file
INFO - Loading variants metadata
Level 9 - Loading row group 0
INFO - Loading regions
Level 9 - Selecting target regions with specific chromosome
Level 9 - Selecting target regions from sub-batches
Level 9 - generating GWAS whitelist
INFO - Loading gwas
INFO - Acquiring filter tree for 227041 targets
INFO - Processing gwas source
Level 9 - Loaded 59616 GWAS variants
Level 9 - Parsing GWAS
Level 9 - Processing region 1/14 [10583.0, 1961168.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,10583.0,1961168.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 2/14 [1961168.0, 3666172.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,1961168.0,3666172.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 3/14 [3666172.0, 4320751.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,3666172.0,4320751.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 4/14 [4320751.0, 5853833.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,4320751.0,5853833.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 5/14 [5853833.0, 7187275.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,5853833.0,7187275.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 6/14 [7187275.0, 9305140.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,7187275.0,9305140.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 7/14 [9305140.0, 10746927.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,9305140.0,10746927.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 8/14 [10746927.0, 11717784.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,10746927.0,11717784.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 9/14 [11717784.0, 12719464.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,11717784.0,12719464.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 10/14 [12719464.0, 14565015.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,12719464.0,14565015.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 11/14 [14565015.0, 16571235.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,14565015.0,16571235.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 12/14 [16571235.0, 18336405.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,16571235.0,18336405.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 13/14 [18336405.0, 20142656.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,18336405.0,20142656.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
Level 9 - Processing region 14/14 [20142656.0, 21410095.0]
Level 8 - Roll out imputation
Level 8 - Preparing data
INFO - Error for region (1,20142656.0,21410095.0): AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'")
INFO - Finished in 75.25838277116418 seconds**

On further inspection, it appears that this error is originating from this function call ("variants = _get_variants(context, ids)") from line 109 in summary-gwas-imputation/src/genomic_tools_lib/summary_imputation/SmmaryInputation.py script

Any advice would be much appreciated.

Best wishes,

Nay

**Comment by Heroico** [comment]
Hi Nay,

Some users have reported this same issue (**AttributeError("'pyarrow.lib.ChunkedArray' object has no attribute 'name'"**). It seems related to underlying software versions, or environment issues.

Are you running on a local PC, or on an HPC cluster? Are you using conda?

I suggest trying with a pyarrow library version at `pyarrow==0.9.0`.

Best,

Alvaro

**Comment by nay421** [comment]
Thank you. Installing pyarrow version 0.9.0 solved the problem.

**Comment by Heroico** [comment]
Hi Nay, thanks for getting back to me. I'm glad to hear the issue got solved.
Best,

Alvaro
