### ISSUE TITLE
Spredixcan.py output effect_size column NA

### ISSUE THREAD

**Issue by wondersyan** [hakyimlab/MetaXcan#97]
Thank you for the nice software and update to GTEX v8!

I'm running python 3 based SprediXcan.py.

I would like to ask, is there a command to use to get other than NA to the effect_size column in the output?
I did full harmonization for my gwas (no imputation) and tested options 
--beta_column
--zscore_column
--pvalue_column
options, but they all gave same results with values in the zscore-column, while effect_size column was NA in the output.

**Comment by Heroico** [comment]
Good day,

The combination `--beta_column` and `se_column` should yield effect sizes.
Please bear in mind that gene-level `effect_size` estimation is much noisier than gene-level `zscore`.

**Comment by wondersyan** [comment]
Thanks, got it working. But in addition to
 `--beta_column` and `se_column` I needed to define
`--zscore_column` too.

**Comment by Heroico** [comment]
What did you need `--zscore_column` for? On my end, I can run S-PrediXcan with only `beta` and `se`. Can I ask you to copy your full command here?

**Comment by wondersyan** [comment]
Sorry, my mistake! I ran my scirpts again and `zscore_column` was NOT needed to see effect sizes. (Therefore, I could remove me earlier comment.. )
