### ISSUE TITLE
Gene names in sMultixcan output for sQTL models

### ISSUE THREAD

**Issue by nay421** [hakyimlab/MetaXcan#99]
Hi, 

In the sMultixcan output using GTEx v8 sQTL database, the gene names are encoded as 'intron_chromosome_start_end'. How can we link this back to the gene symbol?

**Comment by Heroico** [comment]
Good day,

Although the output column is called "gene", when using sQTL models the output is actually an intron event, not genes.
If you want to map to genes, you can download GTEx mapping: [GTEx_Analysis_v8_sQTL_groups.tar.gz](https://storage.googleapis.com/gtex_analysis_v8/single_tissue_qtl_data/GTEx_Analysis_v8_sQTL_groups.tar.gz) from the [GTEx portal](https://gtexportal.org/home/datasets). There is one file per tissue, and the first column looks like:
`chr20:50942126:50945737:clu_24957:ENSG00000000419.12`. You can  build the intron name from the first three fields separated by `:`, and the last field is the gene id. 

If you want a gene id, you would have to use the gene annotation from the GTEx portal [gencode v26](https://storage.googleapis.com/gtex_analysis_v8/reference/gencode.v26.GRCh38.genes.gtf)

**Comment by nay421** [comment]
Thank you @Heroico. I have closed this thread.
